class MethodCallError5 {
    void test() {
        println(foo(1));
    }
}
